import type { Metadata } from "next";
import "./globals.css";
import { Rowdies } from "next/font/google";
import clsx from "clsx";
import Providers from "./provider";

const rowdies = Rowdies({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Avacus - DeBingo",
  description: "Generated by Avacus.cc",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(rowdies.className, "bg-home bg-cover")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
